# This file was generated by GoReleaser. DO NOT EDIT.
cask "rootly-tui" do
  name "rootly-tui"
  desc "Terminal UI for Rootly incidents and alerts"
  homepage "https://rootly.com"
  version "0.2.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "rootly-tui"

  on_macos do
    on_intel do
      url "https://github.com/rootlyhq/rootly-tui/releases/download/v#{version}/rootly-tui_#{version}_darwin_amd64.tar.gz"
      sha256 "5884385b6c7d9047c6868d515c959a112ef97fba7e4d60649133f5b009cadd0a"
    end
    on_arm do
      url "https://github.com/rootlyhq/rootly-tui/releases/download/v#{version}/rootly-tui_#{version}_darwin_arm64.tar.gz"
      sha256 "9084be9a46d2fcfd3575261dc1e4142bb9dfc1a2cedb0cc67c31af25d785adba"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/rootlyhq/rootly-tui/releases/download/v#{version}/rootly-tui_#{version}_linux_amd64.tar.gz"
      sha256 "f80c1a4a30e516c60e9165f0d2f1f08360335121786b6462608c59aa307300eb"
    end
    on_arm do
      url "https://github.com/rootlyhq/rootly-tui/releases/download/v#{version}/rootly-tui_#{version}_linux_arm64.tar.gz"
      sha256 "d43d282ef11a0d88451005ebe0bc72bf1bc5390e970931f3fda3ba3c7a94eb6f"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/rootly-tui"]
    end
  end

  # No zap stanza required
end
