# This file was generated by GoReleaser. DO NOT EDIT.
cask "rootly-tui" do
  name "rootly-tui"
  desc "Terminal UI for Rootly incidents and alerts"
  homepage "https://rootly.com"
  version "0.2.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "rootly-tui"

  on_macos do
    on_intel do
      url "https://github.com/rootlyhq/rootly-tui/releases/download/v#{version}/rootly-tui_#{version}_darwin_amd64.tar.gz"
      sha256 "505add9e577117ed43f4a1077b2f53903732647e0b5ff2dfaaacea130ca0a372"
    end
    on_arm do
      url "https://github.com/rootlyhq/rootly-tui/releases/download/v#{version}/rootly-tui_#{version}_darwin_arm64.tar.gz"
      sha256 "bf3ef5b68797c7fa08503a125a0ffda7a8895dc3c1be36a7d63ce9665aff3a2c"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/rootlyhq/rootly-tui/releases/download/v#{version}/rootly-tui_#{version}_linux_amd64.tar.gz"
      sha256 "e1c1ec703227d5861c4703dc9f3923009e5979c8d21e58c2ac9ff1699b90571d"
    end
    on_arm do
      url "https://github.com/rootlyhq/rootly-tui/releases/download/v#{version}/rootly-tui_#{version}_linux_arm64.tar.gz"
      sha256 "3e204c33a1bb245607a0f49acc9f66a9fcdc1921bb6f12dda259d9819170665f"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/rootly-tui"]
    end
  end

  # No zap stanza required
end
