# This file was generated by GoReleaser. DO NOT EDIT.
cask "rootly-tui" do
  version "0.4.0"

  on_macos do
    on_intel do
      sha256 "d6c8c394d38eaaa62a036e41d4c99799c96f2d6f2b30a2d87bdc487713f0da2e"
      url "https://github.com/rootlyhq/rootly-tui/releases/download/v#{version}/rootly-tui_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "1d9da37eb5b7f63624a37d1d3bde0df7a42bdaf5dbb8f00810c1aed5dc61032d"
      url "https://github.com/rootlyhq/rootly-tui/releases/download/v#{version}/rootly-tui_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "da7373e47ce73c245f48f9a5694b1198b76dc17189f61b62205559d97fb7c287"
      url "https://github.com/rootlyhq/rootly-tui/releases/download/v#{version}/rootly-tui_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "55f55452348f96eef4a8cf8d3478c2875b6873992feb4b7842b030c5dc36bf75"
      url "https://github.com/rootlyhq/rootly-tui/releases/download/v#{version}/rootly-tui_#{version}_linux_arm64.tar.gz"
    end
  end

  name "rootly-tui"
  desc "Terminal UI for Rootly incidents and alerts"
  homepage "https://rootly.com"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "rootly-tui"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/rootly-tui"]
    end
  end

  # No zap stanza required

end
