# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cli < Formula
  desc "Command line tool for rootly.io"
  homepage "https://rootly.io"
  version "0.0.2"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/rootly-io/cli/releases/download/v0.0.2/cli_0.0.2_darwin_amd64.tar.gz"
    sha256 "3b2a4ab1e7d08997dfbe8f5742f36f70ae10e13d7d13d99baf7f56c86c167b19"
  end
  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/rootly-io/cli/releases/download/v0.0.2/cli_0.0.2_darwin_arm64.tar.gz"
    sha256 "8ec2261f3c966fe445675620500dfd06abac4ada0437c22ad3ecf9f1b314d11e"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/rootly-io/cli/releases/download/v0.0.2/cli_0.0.2_linux_amd64.tar.gz"
    sha256 "4400866a9ef9079f13efc0d30710855065019616a954b64566d567413b79d808"
  end
  if OS.linux? && Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
    url "https://github.com/rootly-io/cli/releases/download/v0.0.2/cli_0.0.2_linux_armv6.tar.gz"
    sha256 "b3ed8211a633c5321f2ffc36d5425f3519ae0abc7e3edebb7298dde035d0a334"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/rootly-io/cli/releases/download/v0.0.2/cli_0.0.2_linux_arm64.tar.gz"
    sha256 "e8d9b86e387a83658049ed8f3e7a2d21429c2ef97631684225ab1b7245f7c9a1"
  end

  def install
    bin.install "rootly"
  end
end
