# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cli < Formula
  desc "Command line tool for rootly.io"
  homepage "https://rootly.io"
  version "0.0.1"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/rootly-io/cli/releases/download/v0.0.1/cli_0.0.1_darwin_amd64.tar.gz"
    sha256 "8419b8ea28941769999150ac019a74458b1b3da7398093f7d968c8e2ca7276d3"
  end
  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/rootly-io/cli/releases/download/v0.0.1/cli_0.0.1_darwin_arm64.tar.gz"
    sha256 "55cb7f2ec0904cc6522f7f27c39971be8b3e54dfc047ee9c7232ad0375cf9cd0"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/rootly-io/cli/releases/download/v0.0.1/cli_0.0.1_linux_amd64.tar.gz"
    sha256 "f535b947222f274b40d53931f7df1f1cb2e9e93da7140c087814990791069384"
  end
  if OS.linux? && Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
    url "https://github.com/rootly-io/cli/releases/download/v0.0.1/cli_0.0.1_linux_armv6.tar.gz"
    sha256 "6a0b878e54c5ea3e0dd4581133701fbf9e4a4fc7ced2148c1ea66cf6d9e2abc7"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/rootly-io/cli/releases/download/v0.0.1/cli_0.0.1_linux_arm64.tar.gz"
    sha256 "d2b76917e75ca806cd42d3adaf841783f468ff8bdfd0b7af01283fa6bb573252"
  end

  def install
    bin.install "rootly"
  end
end
