# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cli < Formula
  desc "Command line tool for rootly.io"
  homepage "https://rootly.io"
  version "0.0.2"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/rootly-io/cli/releases/download/v0.0.2/cli_0.0.2_darwin_amd64.tar.gz"
    sha256 "c843ceb9244cba1487b5a4dda6499e62b88b9da8277612ab8a8ca9471dc5141a"
  end
  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/rootly-io/cli/releases/download/v0.0.2/cli_0.0.2_darwin_arm64.tar.gz"
    sha256 "a72c2ce1f581b94f6f6fc0990f341567649aea7423e7162f63916da4442b1ba7"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/rootly-io/cli/releases/download/v0.0.2/cli_0.0.2_linux_amd64.tar.gz"
    sha256 "7fbc5648bf413988edb9b7737f2656fa8ffe8ea3e3a5696335609ebff7abb4fc"
  end
  if OS.linux? && Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
    url "https://github.com/rootly-io/cli/releases/download/v0.0.2/cli_0.0.2_linux_armv6.tar.gz"
    sha256 "85ff23776f4684c4e096a24904678066d9a4a87a58dc6b89accdb54ee4293e73"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/rootly-io/cli/releases/download/v0.0.2/cli_0.0.2_linux_arm64.tar.gz"
    sha256 "63be7b4d9ffeb1edc886d941a57efe8eca3f9d801b271a6bae30a3d6c43e27a9"
  end

  def install
    bin.install "rootly"
  end
end
