# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class RootlyCatalogSync < Formula
  desc "Sync external catalog data into Rootly"
  homepage "https://github.com/rootlyhq/rootly-catalog-sync"
  version "0.2.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rootlyhq/rootly-catalog-sync/releases/download/v0.2.1/rootly-catalog-sync_0.2.1_darwin_amd64.tar.gz"
      sha256 "c1c06b5c42307e5bb3336bdb0a20aee000cb045d60fb4882f115bdc6809dc9fd"

      define_method(:install) do
        bin.install "rootly-catalog-sync"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/rootlyhq/rootly-catalog-sync/releases/download/v0.2.1/rootly-catalog-sync_0.2.1_darwin_arm64.tar.gz"
      sha256 "b053aa78c3770bf9b67acbdedcf2172191c09208c3db33112035b2d68d77edef"

      define_method(:install) do
        bin.install "rootly-catalog-sync"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/rootlyhq/rootly-catalog-sync/releases/download/v0.2.1/rootly-catalog-sync_0.2.1_linux_amd64.tar.gz"
      sha256 "c5bfaf79da771d95276778c16be09726a20118a70b28447c7cdffef7fb3bae95"
      define_method(:install) do
        bin.install "rootly-catalog-sync"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rootlyhq/rootly-catalog-sync/releases/download/v0.2.1/rootly-catalog-sync_0.2.1_linux_arm64.tar.gz"
      sha256 "20dd6e1b220322c7b49d2630e75d63099b5e27217568c23d2ef3aa8f6f872c04"
      define_method(:install) do
        bin.install "rootly-catalog-sync"
      end
    end
  end

  test do
    system "#{bin}/rootly-catalog-sync", "version"
  end
end
