# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class RootlyEdgeConnector < Formula
  desc "Rootly Edge Connector - Execute custom actions in response to Rootly events"
  homepage "https://github.com/rootlyhq/rootly-edge-connector"
  version "0.0.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rootlyhq/rootly-edge-connector/releases/download/v0.0.1/rootly-edge-connector_0.0.1_darwin_amd64.tar.gz"
      sha256 "2716ac9dc018af3e58d3eba2b6028594f92ffada0b3bedee219eb075ee225034"

      def install
        bin.install "rootly-edge-connector"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/rootlyhq/rootly-edge-connector/releases/download/v0.0.1/rootly-edge-connector_0.0.1_darwin_arm64.tar.gz"
      sha256 "0e37c75ffa491b67f62dd8ef7dfa6016dd59dbaefd7cc8ecac442289bac99320"

      def install
        bin.install "rootly-edge-connector"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/rootlyhq/rootly-edge-connector/releases/download/v0.0.1/rootly-edge-connector_0.0.1_linux_amd64.tar.gz"
      sha256 "b6e44eeb67bf41d6667e7dbc989d56f4c45068d56f346f845af37574e9cd42dd"
      def install
        bin.install "rootly-edge-connector"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/rootlyhq/rootly-edge-connector/releases/download/v0.0.1/rootly-edge-connector_0.0.1_linux_arm.tar.gz"
      sha256 "c89d6ab62079f47abb1f1f0aeb4c3d473f5011ce1291dd2b9065ca39bd0a69ae"
      def install
        bin.install "rootly-edge-connector"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rootlyhq/rootly-edge-connector/releases/download/v0.0.1/rootly-edge-connector_0.0.1_linux_arm64.tar.gz"
      sha256 "690ce3f7e0023e9f7b2fbe6057074d53008578bef0eeab949163d6b87dc9bbec"
      def install
        bin.install "rootly-edge-connector"
      end
    end
  end

  test do
    system "#{bin}/rootly-edge-connector", "--version"
  end
end
