# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Rootly < Formula
  desc "Command line tool for rootly.io"
  homepage "https://rootly.io"
  version "0.0.1"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/rootly-io/cli/releases/download/v0.0.1/rootly_0.0.1_darwin_amd64.tar.gz"
    sha256 "288bb677a12ae847695275d1248639e211d7f92d323118af32709592c928d192"
  end
  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/rootly-io/cli/releases/download/v0.0.1/rootly_0.0.1_darwin_arm64.tar.gz"
    sha256 "89fb837e9110f5b7982e197611990385285613f41fca82be4b927b8a38ccfaf4"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/rootly-io/cli/releases/download/v0.0.1/rootly_0.0.1_linux_amd64.tar.gz"
    sha256 "fc3c2a101294ceaf4aa4426a2a2ce8eae06595442a7858d7fddb99c18ece83c6"
  end
  if OS.linux? && Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
    url "https://github.com/rootly-io/cli/releases/download/v0.0.1/rootly_0.0.1_linux_armv6.tar.gz"
    sha256 "08f3e8a46085f1de9b7d1c66dd7e00eceaf2d4e8cf16378667790bb3ab6b8d6d"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/rootly-io/cli/releases/download/v0.0.1/rootly_0.0.1_linux_arm64.tar.gz"
    sha256 "58b9213f034505980d37bc966a44732ba5a7e8823a57509fa0eabc9328f83bfb"
  end

  def install
    bin.install "rootly"
  end
end
