# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class RootlyEdgeConnector < Formula
  desc "Rootly Edge Connector - Execute custom actions in response to Rootly events"
  homepage "https://github.com/rootlyhq/rootly-edge-connector"
  version "0.0.3"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rootlyhq/rootly-edge-connector/releases/download/v0.0.3/rootly-edge-connector_0.0.3_darwin_amd64.tar.gz"
      sha256 "d06c1c1cc9cf7a7518b6501cda34460c11c3c273bdf99d8f8fe252fccff235e2"

      def install
        bin.install "rootly-edge-connector"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/rootlyhq/rootly-edge-connector/releases/download/v0.0.3/rootly-edge-connector_0.0.3_darwin_arm64.tar.gz"
      sha256 "59a6b6522bcc27b5380424ac7724a77e87abf3c35f0e1c5ceacf40cb648e9360"

      def install
        bin.install "rootly-edge-connector"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/rootlyhq/rootly-edge-connector/releases/download/v0.0.3/rootly-edge-connector_0.0.3_linux_amd64.tar.gz"
      sha256 "a46f86780913088899146a9fbda5c9ce3b25d18b1649be69ee683cecc8db49c1"
      def install
        bin.install "rootly-edge-connector"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/rootlyhq/rootly-edge-connector/releases/download/v0.0.3/rootly-edge-connector_0.0.3_linux_arm.tar.gz"
      sha256 "eeeb2837e24810136b79bb58c964d51f0eeb32892a160a9df1ad59133e33ba72"
      def install
        bin.install "rootly-edge-connector"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rootlyhq/rootly-edge-connector/releases/download/v0.0.3/rootly-edge-connector_0.0.3_linux_arm64.tar.gz"
      sha256 "09346f4882a8fd9a860c980cab56f6e97aeaa6bbcaf82243aabcd9a657d26355"
      def install
        bin.install "rootly-edge-connector"
      end
    end
  end

  test do
    system "#{bin}/rootly-edge-connector", "--version"
  end
end
