# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class RootlyCatalogSync < Formula
  desc "Sync external catalog data into Rootly"
  homepage "https://github.com/rootlyhq/rootly-catalog-sync"
  version "0.3.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rootlyhq/rootly-catalog-sync/releases/download/v0.3.3/rootly-catalog-sync_0.3.3_darwin_amd64.tar.gz"
      sha256 "06163e5b2ef37d43ecb5eefe682b01e2f62471a2dc004236d119ec0753754e08"

      define_method(:install) do
        bin.install "rootly-catalog-sync"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/rootlyhq/rootly-catalog-sync/releases/download/v0.3.3/rootly-catalog-sync_0.3.3_darwin_arm64.tar.gz"
      sha256 "5031b56603b0abf7888d87e18320e5b0d013bed59d142ea154075863f7b80a08"

      define_method(:install) do
        bin.install "rootly-catalog-sync"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/rootlyhq/rootly-catalog-sync/releases/download/v0.3.3/rootly-catalog-sync_0.3.3_linux_amd64.tar.gz"
      sha256 "a1f1a76f0ddb13f56130e77926f8195f88b8e91436e25ff1c40b4d1f12cbff5b"
      define_method(:install) do
        bin.install "rootly-catalog-sync"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rootlyhq/rootly-catalog-sync/releases/download/v0.3.3/rootly-catalog-sync_0.3.3_linux_arm64.tar.gz"
      sha256 "d2479b92128b09507d5e5684a55f88fdd50598074ba3399d25bff8a9a4d9f769"
      define_method(:install) do
        bin.install "rootly-catalog-sync"
      end
    end
  end

  test do
    system "#{bin}/rootly-catalog-sync", "version"
  end
end
