# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class RootlyCli < Formula
  desc "Rootly CLI for managing incidents, alerts, and workflows"
  homepage "https://rootly.com"
  version "0.4.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rootlyhq/rootly-cli/releases/download/v0.4.1/rootly-cli_0.4.1_darwin_amd64.tar.gz"
      sha256 "95c65d4e84b3dc61e58180ec2f8602cc39930179ec723ce5864dcb933ef20cf5"

      define_method(:install) do
        bin.install "rootly"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/rootlyhq/rootly-cli/releases/download/v0.4.1/rootly-cli_0.4.1_darwin_arm64.tar.gz"
      sha256 "af8fee9401cd9ede34e6ca6d3ada6f4e553d0222ac0d5d58c819e4920b2fdb55"

      define_method(:install) do
        bin.install "rootly"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/rootlyhq/rootly-cli/releases/download/v0.4.1/rootly-cli_0.4.1_linux_amd64.tar.gz"
      sha256 "d70e531285de6377a87f5aecc8103d7276f8c79c577b55781daaafdaa93007a0"
      define_method(:install) do
        bin.install "rootly"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rootlyhq/rootly-cli/releases/download/v0.4.1/rootly-cli_0.4.1_linux_arm64.tar.gz"
      sha256 "96c7ee771a9529cbba382ad1e532a5360593585e0d177ada19911c0c5e3bc1c2"
      define_method(:install) do
        bin.install "rootly"
      end
    end
  end

  test do
    system "#{bin}/rootly", "version"
  end
end
