# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class RootlyCli < Formula
  desc "Rootly CLI for managing incidents, alerts, and workflows"
  homepage "https://rootly.com"
  version "0.1.5"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rootlyhq/rootly-cli/releases/download/v0.1.5/rootly-cli_0.1.5_darwin_amd64.tar.gz"
      sha256 "e8e88f6aaeb291fecc05218add95f790f785f48bb7bae3611f50bb6c404905a2"

      define_method(:install) do
        bin.install "rootly"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/rootlyhq/rootly-cli/releases/download/v0.1.5/rootly-cli_0.1.5_darwin_arm64.tar.gz"
      sha256 "c07dfa4cbda178d1ae266f965c045f6b2470d7eb8dd7491eefe39b5d729fb3d1"

      define_method(:install) do
        bin.install "rootly"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/rootlyhq/rootly-cli/releases/download/v0.1.5/rootly-cli_0.1.5_linux_amd64.tar.gz"
      sha256 "5f089438eee5d18cdc114ef82562b362d76ed36fe6ee79b422d26e7144f991a8"
      define_method(:install) do
        bin.install "rootly"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rootlyhq/rootly-cli/releases/download/v0.1.5/rootly-cli_0.1.5_linux_arm64.tar.gz"
      sha256 "eebba64bfcfa4f9d614a25ffa8ce3bace668e3035499e32a8cf5775ce148f6a5"
      define_method(:install) do
        bin.install "rootly"
      end
    end
  end

  test do
    system "#{bin}/rootly", "version"
  end
end
