# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Rootly < Formula
  desc "Command line tool for rootly.io"
  homepage "https://rootly.io"
  version "1.0.1"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/rootly-io/cli/releases/download/v1.0.1/rootly_1.0.1_darwin_amd64.tar.gz"
    sha256 "c7a5b624b4d340df044a7b442332d726aff51a97127955e175d0d1267ad11945"
  end
  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/rootly-io/cli/releases/download/v1.0.1/rootly_1.0.1_darwin_arm64.tar.gz"
    sha256 "b6005d69e4e9060d58abcfb26e04e5ba6f307932210bc9f38d9cf576cb297e05"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/rootly-io/cli/releases/download/v1.0.1/rootly_1.0.1_linux_amd64.tar.gz"
    sha256 "0c4af2b4d05d6a21fd1741523d2af01f2a193fd93c34dd8ff376b5f117b27c33"
  end
  if OS.linux? && Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
    url "https://github.com/rootly-io/cli/releases/download/v1.0.1/rootly_1.0.1_linux_armv6.tar.gz"
    sha256 "c1dfe63757932c623bb4f357ddee3bf873f2a77d693af981e37649b289a56a28"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/rootly-io/cli/releases/download/v1.0.1/rootly_1.0.1_linux_arm64.tar.gz"
    sha256 "74a0922073f7f842813199629ba72a5184ae9e491ceda236cf9050cfac60cf70"
  end

  def install
    bin.install "rootly"
  end
end
