# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class RootlyCatalogSync < Formula
  desc "Sync external catalog data into Rootly"
  homepage "https://github.com/rootlyhq/rootly-catalog-sync"
  version "0.5.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rootlyhq/rootly-catalog-sync/releases/download/v0.5.0/rootly-catalog-sync_0.5.0_darwin_amd64.tar.gz"
      sha256 "75d4cade63f100866129378d02d385518de64752cf8d027102944b77407b0e8a"

      define_method(:install) do
        bin.install "rootly-catalog-sync"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/rootlyhq/rootly-catalog-sync/releases/download/v0.5.0/rootly-catalog-sync_0.5.0_darwin_arm64.tar.gz"
      sha256 "e8ba8573d5400a48127b21d4f7f8dbc7d04d7b56979c046e4ab9f0c780cf54c6"

      define_method(:install) do
        bin.install "rootly-catalog-sync"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/rootlyhq/rootly-catalog-sync/releases/download/v0.5.0/rootly-catalog-sync_0.5.0_linux_amd64.tar.gz"
      sha256 "1879b9cff74d62ef598c41d063535e834a916274cadab125b89a0ab87ef4be6c"
      define_method(:install) do
        bin.install "rootly-catalog-sync"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rootlyhq/rootly-catalog-sync/releases/download/v0.5.0/rootly-catalog-sync_0.5.0_linux_arm64.tar.gz"
      sha256 "01783a54ae840c47dc6b866f1d9d50d5c2950b381afc6e616a52792456069b3b"
      define_method(:install) do
        bin.install "rootly-catalog-sync"
      end
    end
  end

  test do
    system "#{bin}/rootly-catalog-sync", "version"
  end
end
